services:
  - type: web
    name: etaklifnoma
    plan: free
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: APP_URL
        value: https://etaklifnoma.uz
      - key: VERIFY_BOT_TOKEN
        value: 8766115817:AAE1Z6UZdJDyG94iJYWrpEJIENjsGB3iu4k
      - key: VERIFY_CHAT_ID
        value: "5887503077"
      - key: TELEGRAM_BOT_TOKEN
        value: 8766115817:AAE1Z6UZdJDyG94iJYWrpEJIENjsGB3iu4k
      - key: SUPPORT_BOT_TOKEN
        value: 8736965523:AAHbza3gP_H2N-6ZQctyrFjenom55CfKWhc
      - key: SUPPORT_CHAT_ID
        value: "5887503077"
